packages:
  - "mcp"
overrides:
  diff: ">=8.0.3"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@tsparticles/engine': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
